### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by musicinmybrain** [biojppm/cmake#2]
Could you please add an explicit license statement for this project, preferably including a separate `LICENSE.txt` or similar file?

These scripts need a license before I can distribute them, which is necessary in order for me to package [c4core](https://github.com/biojppm/c4core/), and ultimately [rapidyaml](https://github.com/biojppm/rapidyaml/), for Fedora Linux.

(Note that `Toolchain-PS4.cmake` and `Toolchain-XBoxOne.cmake` are already under the [Apache License, version 2.0](https://apache.org/licenses/LICENSE-2.0.html), but any compatible FOSS license will work here.)

Thanks!

**Comment by biojppm** [comment]
@musicinmybrain done. Thanks for reporting!

**Comment by musicinmybrain** [comment]
Thanks!
