### ISSUE TITLE
Intent of removing .so versions from c4core/c4log/c4fs?

### ISSUE THREAD

**Issue by musicinmybrain** [biojppm/cmake#8]
I’ve packaged `c4core`, `c4log`, and `c4fs` on Fedora Linux in preparation for packaging `rapidyaml` (almost done!)

The change in https://github.com/biojppm/cmake/commit/436b163de715eb01e0912ea329431ca4c942a6ba means that these libraries no longer have an `SONAME`, so I would have to either:

1. start [versioning the libraries downstream](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_downstream_so_name_versioning) (basically, carry a patch reverting this commit forever)—which is feasible—or
2. give up on packaging these libraries separately from `rapidyaml`—which I am [permitted to do, subject to conditions](https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling), if I absolutely have to, but which has [disadvantages](https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries#Why_Bundled_Libraries_are_a_problem) from a distribution packager’s point of view.

Is this the intended effect of this commit? Does it solve a problem in a different environment? Can it be conditionalized such that I can turn versioning back on when packaging system copies of these libraries?

Thanks!

**Comment by musicinmybrain** [comment]
> c4core and friends are definitely meant to have versioning - that's why that is done in this project, so that any lib that uses this is dealt with in the same way. I will try to figure this out.

Thanks! Let me know if I can do anything to help.

**Comment by musicinmybrain** [comment]
@biojppm, did you have any luck figuring out why this was happening? Thanks!

**Comment by biojppm** [comment]
Sorry, forgot about this.

I investigated and turns out [the proper name is `SOVERSION`](https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html) rather than `SO_VERSION`.

I don't know how it worked before, but there it is.

**Comment by musicinmybrain** [comment]
> […] I investigated and turns out [the proper name is `SOVERSION`](https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html) rather than `SO_VERSION`. […]

Thanks! This now seems to work as intended.
