### ISSUE TITLE
How to build rapidyaml ?

### ISSUE THREAD

**Issue by amarnathreddy0201** [biojppm/cmake#9]
Hi Sir,
1) Creating build and cd build
2) From build folder cmake .. (is this right ?)
3) cmake --build . (For building)

I am failing at 2nd step and it given blow error

```
CMake Error at CMakeLists.txt:9 (c4_project):
  Unknown CMake command "c4_project".
```

I am using windows OS.
Thanks,
ANR .S

**Comment by biojppm** [comment]
It is missing the git submodules. As indicated in the readme and in the samples, use git clone --recursive.
